//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaggiaTrentino.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViaggiaTrentino.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViaggiaTrentino.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViaggiaTrentino.
        /// </summary>
        public static string MainViewTitle {
            get {
                return ResourceManager.GetString("MainViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time Information.
        /// </summary>
        public static string RealTimeInfoViewTitle {
            get {
                return ResourceManager.GetString("RealTimeInfoViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete journey.
        /// </summary>
        public static string SavedJourneyDetailsDelete {
            get {
                return ResourceManager.GetString("SavedJourneyDetailsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable monitoring.
        /// </summary>
        public static string SavedJourneyDetailsMonitorOff {
            get {
                return ResourceManager.GetString("SavedJourneyDetailsMonitorOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable monitoring.
        /// </summary>
        public static string SavedJourneyDetailsMonitorOn {
            get {
                return ResourceManager.GetString("SavedJourneyDetailsMonitorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journeys.
        /// </summary>
        public static string SavedJourneysJourneyPivot {
            get {
                return ResourceManager.GetString("SavedJourneysJourneyPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string SavedJourneysMonitoringPivot {
            get {
                return ResourceManager.GetString("SavedJourneysMonitoringPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved journeys.
        /// </summary>
        public static string SavedJourneysTitle {
            get {
                return ResourceManager.GetString("SavedJourneysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a single journey.
        /// </summary>
        public static string TilePlanJourneyMessagTilePlanJourneyMessagTilePlanJourneyMessageTilePlanJourneyMessage {
            get {
                return ResourceManager.GetString("TilePlanJourneyMessagTilePlanJourneyMessagTilePlanJourneyMessageTilePlanJourneyMe" +
                        "ssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan journey.
        /// </summary>
        public static string TilePlanJourneyTitle {
            get {
                return ResourceManager.GetString("TilePlanJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a recurrent journey.
        /// </summary>
        public static string TilePlanRecurrentJourneyMessage {
            get {
                return ResourceManager.GetString("TilePlanRecurrentJourneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan recurrent journey.
        /// </summary>
        public static string TilePlanRecurrentJourneyTitle {
            get {
                return ResourceManager.GetString("TilePlanRecurrentJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all notifications.
        /// </summary>
        public static string TileReadNotificationsMessage {
            get {
                return ResourceManager.GetString("TileReadNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read notification.
        /// </summary>
        public static string TileReadNotificationsTitle {
            get {
                return ResourceManager.GetString("TileReadNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show realtime info.
        /// </summary>
        public static string TileRealTimeInfoMessage {
            get {
                return ResourceManager.GetString("TileRealTimeInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time info.
        /// </summary>
        public static string TileRealTimeInfoTitle {
            get {
                return ResourceManager.GetString("TileRealTimeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my saved journeys.
        /// </summary>
        public static string TileSavedJourneysMessage {
            get {
                return ResourceManager.GetString("TileSavedJourneysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved journeys.
        /// </summary>
        public static string TileSavedJourneysTitle {
            get {
                return ResourceManager.GetString("TileSavedJourneysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an alert.
        /// </summary>
        public static string TileSubmitAlertMessage {
            get {
                return ResourceManager.GetString("TileSubmitAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit alert.
        /// </summary>
        public static string TileSubmitAlertTitle {
            get {
                return ResourceManager.GetString("TileSubmitAlertTitle", resourceCulture);
            }
        }
    }
}
