//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaggiaTrentino.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViaggiaTrentino.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ViaggiaTrentino.
        /// </summary>
        public static string AboTitle {
            get {
                return ResourceManager.GetString("AboTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In collaborazione con il Comune di Trento.
        /// </summary>
        public static string AboutPageCollab {
            get {
                return ResourceManager.GetString("AboutPageCollab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;applicazione è stata sviluppata dal progetto SmartCampus.
        /// </summary>
        public static string AboutPageDevel {
            get {
                return ResourceManager.GetString("AboutPageDevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazione sulla mobilità integrata di Trento e dei comuni trentini.
        /// </summary>
        public static string AboutPageInfo {
            get {
                return ResourceManager.GetString("AboutPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con la partecipazione del Consorzio dei Comuni Trentini.
        /// </summary>
        public static string AboutPagePart {
            get {
                return ResourceManager.GetString("AboutPagePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate me!.
        /// </summary>
        public static string AboutPageRateApp {
            get {
                return ResourceManager.GetString("AboutPageRateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third party.
        /// </summary>
        public static string AboutPageThird {
            get {
                return ResourceManager.GetString("AboutPageThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application includes the following third party software:.
        /// </summary>
        public static string AboutPageThirdParty {
            get {
                return ResourceManager.GetString("AboutPageThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tile has already been pinned!.
        /// </summary>
        public static string AlreadyPinnedTileError {
            get {
                return ResourceManager.GetString("AlreadyPinnedTileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViaggiaTrentino.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow this application to access and use your location?.
        /// </summary>
        public static string AppLocationDisabledCaption {
            get {
                return ResourceManager.GetString("AppLocationDisabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is disabled on your app. Do you want to enable it?.
        /// </summary>
        public static string AppLocationDisabledMessage {
            get {
                return ResourceManager.GetString("AppLocationDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMARTCAMPUS LAB.
        /// </summary>
        public static string AppProducer {
            get {
                return ResourceManager.GetString("AppProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the course of the last week, the application encountered a few minor errors. Would you like to report them?.
        /// </summary>
        public static string CatchedErrorsReportMessage {
            get {
                return ResourceManager.GetString("CatchedErrorsReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string CatchedHttpErrorMessage {
            get {
                return ResourceManager.GetString("CatchedHttpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing our data..
        /// </summary>
        public static string CatchedParseErrorMessage {
            get {
                return ResourceManager.GetString("CatchedParseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected location:.
        /// </summary>
        public static string ChooseConfirmTitle {
            get {
                return ResourceManager.GetString("ChooseConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current location.
        /// </summary>
        public static string ChooseCurrent {
            get {
                return ResourceManager.GetString("ChooseCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your mobile&apos;s GPS position.
        /// </summary>
        public static string ChooseCurrentLong {
            get {
                return ResourceManager.GetString("ChooseCurrentLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point on map.
        /// </summary>
        public static string ChoosePoint {
            get {
                return ResourceManager.GetString("ChoosePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a point from an onscreen map.
        /// </summary>
        public static string ChoosePointLong {
            get {
                return ResourceManager.GetString("ChoosePointLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location.
        /// </summary>
        public static string ChooseTitle {
            get {
                return ResourceManager.GetString("ChooseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data.
        /// </summary>
        public static string DefValueMissing {
            get {
                return ResourceManager.GetString("DefValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reporting.
        /// </summary>
        public static string ErrorReportCaption {
            get {
                return ResourceManager.GetString("ErrorReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application seems to have encountered some difficulties during the last run. Do you want to send a report of the application error to help improve the experience?.
        /// </summary>
        public static string ErrorReportMessage {
            get {
                return ResourceManager.GetString("ErrorReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike.
        /// </summary>
        public static string GeneralSettingsBike {
            get {
                return ResourceManager.GetString("GeneralSettingsBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string GeneralSettingsCar {
            get {
                return ResourceManager.GetString("GeneralSettingsCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        public static string GeneralSettingsFastest {
            get {
                return ResourceManager.GetString("GeneralSettingsFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fewest changes.
        /// </summary>
        public static string GeneralSettingsFewestChanges {
            get {
                return ResourceManager.GetString("GeneralSettingsFewestChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least walking.
        /// </summary>
        public static string GeneralSettingsLeastWalking {
            get {
                return ResourceManager.GetString("GeneralSettingsLeastWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred route.
        /// </summary>
        public static string GeneralSettingsPrefRoute {
            get {
                return ResourceManager.GetString("GeneralSettingsPrefRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared bike.
        /// </summary>
        public static string GeneralSettingsSharedBike {
            get {
                return ResourceManager.GetString("GeneralSettingsSharedBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared car.
        /// </summary>
        public static string GeneralSettingsSharedCar {
            get {
                return ResourceManager.GetString("GeneralSettingsSharedCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit.
        /// </summary>
        public static string GeneralSettingsTransit {
            get {
                return ResourceManager.GetString("GeneralSettingsTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string GeneralSettingsTransportation {
            get {
                return ResourceManager.GetString("GeneralSettingsTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string GeneralSettingsWalking {
            get {
                return ResourceManager.GetString("GeneralSettingsWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GenericErrorTitle {
            get {
                return ResourceManager.GetString("GenericErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for your journey.
        /// </summary>
        public static string JourneyNameMsg {
            get {
                return ResourceManager.GetString("JourneyNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey name.
        /// </summary>
        public static string JourneyNameTit {
            get {
                return ResourceManager.GetString("JourneyNameTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingPanel {
            get {
                return ResourceManager.GetString("LoadingPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MainpageAbout {
            get {
                return ResourceManager.GetString("MainpageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string MainpageLogin {
            get {
                return ResourceManager.GetString("MainpageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string MainpageLogout {
            get {
                return ResourceManager.GetString("MainpageLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainpageSettings {
            get {
                return ResourceManager.GetString("MainpageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tutorial.
        /// </summary>
        public static string MainpageTour {
            get {
                return ResourceManager.GetString("MainpageTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViaggiaTrentino.
        /// </summary>
        public static string MainViewTitle {
            get {
                return ResourceManager.GetString("MainViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow.
        /// </summary>
        public static string MessageBoxAllow {
            get {
                return ResourceManager.GetString("MessageBoxAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string MessageBoxCancel {
            get {
                return ResourceManager.GetString("MessageBoxCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use the application you have to accept Google permissions.
        /// </summary>
        public static string MessageBoxGooglePermsMessage {
            get {
                return ResourceManager.GetString("MessageBoxGooglePermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        public static string MessageBoxGooglePermsTitle {
            get {
                return ResourceManager.GetString("MessageBoxGooglePermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to settings.
        /// </summary>
        public static string MessageBoxGoToSettings {
            get {
                return ResourceManager.GetString("MessageBoxGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to smartcampuslab servers. Check your internet connection and try again..
        /// </summary>
        public static string MessageBoxNetworkErrorBody {
            get {
                return ResourceManager.GetString("MessageBoxNetworkErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string MessageBoxNetworkErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxNetworkErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use the application you have to accept SmartCampus permissions.
        /// </summary>
        public static string MessageBoxSmartCampusPermsMessage {
            get {
                return ResourceManager.GetString("MessageBoxSmartCampusPermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        public static string MessageBoxSmartCampusPermsTitle {
            get {
                return ResourceManager.GetString("MessageBoxSmartCampusPermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string MonitorJourneyAlways {
            get {
                return ResourceManager.GetString("MonitorJourneyAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the transit lines you want to be notified about in case of delays.
        /// </summary>
        public static string MonitorJourneyHeadText {
            get {
                return ResourceManager.GetString("MonitorJourneyHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string MonitorJourneyLoc {
            get {
                return ResourceManager.GetString("MonitorJourneyLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preferences.
        /// </summary>
        public static string MonitorJourneyPrefs {
            get {
                return ResourceManager.GetString("MonitorJourneyPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string MonitorJourneySched {
            get {
                return ResourceManager.GetString("MonitorJourneySched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time span.
        /// </summary>
        public static string MonitorJourneyTimeSpan {
            get {
                return ResourceManager.GetString("MonitorJourneyTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor journey.
        /// </summary>
        public static string MonitorJourneyTitle {
            get {
                return ResourceManager.GetString("MonitorJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring status:.
        /// </summary>
        public static string MonitorStat {
            get {
                return ResourceManager.GetString("MonitorStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ParkingPopupCancel {
            get {
                return ResourceManager.GetString("ParkingPopupCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string ParkingPopupDirections {
            get {
                return ResourceManager.GetString("ParkingPopupDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string ParkingPopupTitle {
            get {
                return ResourceManager.GetString("ParkingPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string ParkingsPageMapPivot {
            get {
                return ResourceManager.GetString("ParkingsPageMapPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkings.
        /// </summary>
        public static string ParkingsPageParkingPivot {
            get {
                return ResourceManager.GetString("ParkingsPageParkingPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time info.
        /// </summary>
        public static string ParkingsPageTitle {
            get {
                return ResourceManager.GetString("ParkingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full.
        /// </summary>
        public static string ParkingsSlotsFull {
            get {
                return ResourceManager.GetString("ParkingsSlotsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go.
        /// </summary>
        public static string PlanConfirm {
            get {
                return ResourceManager.GetString("PlanConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up your usual routes to be notify about possible delays.
        /// </summary>
        public static string PlanRecurrentJourneyTileTagTour {
            get {
                return ResourceManager.GetString("PlanRecurrentJourneyTileTagTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string PlanSave {
            get {
                return ResourceManager.GetString("PlanSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string PlanSingleJourneyDeparture {
            get {
                return ResourceManager.GetString("PlanSingleJourneyDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From....
        /// </summary>
        public static string PlanSingleJourneyHintFrom {
            get {
                return ResourceManager.GetString("PlanSingleJourneyHintFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To....
        /// </summary>
        public static string PlanSingleJourneyHintTo {
            get {
                return ResourceManager.GetString("PlanSingleJourneyHintTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string PlanSingleJourneyLoc {
            get {
                return ResourceManager.GetString("PlanSingleJourneyLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preferences.
        /// </summary>
        public static string PlanSingleJourneyPrefs {
            get {
                return ResourceManager.GetString("PlanSingleJourneyPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan new journey.
        /// </summary>
        public static string PlanSingleJourneyTitle {
            get {
                return ResourceManager.GetString("PlanSingleJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if the bus or train is on time.
        /// </summary>
        public static string ReadNotificationsTileTagTour {
            get {
                return ResourceManager.GetString("ReadNotificationsTileTagTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the local bus or train schedule or find available parking.
        /// </summary>
        public static string RealTimeInfoTileTagTour {
            get {
                return ResourceManager.GetString("RealTimeInfoTileTagTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time Information.
        /// </summary>
        public static string RealTimeInfoViewTitle {
            get {
                return ResourceManager.GetString("RealTimeInfoViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string RoutePivot {
            get {
                return ResourceManager.GetString("RoutePivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string SavedJourneyDetailsDelete {
            get {
                return ResourceManager.GetString("SavedJourneyDetailsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monitor off.
        /// </summary>
        public static string SavedJourneyMonitorOFF {
            get {
                return ResourceManager.GetString("SavedJourneyMonitorOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monitor on.
        /// </summary>
        public static string SavedJourneyMonitorON {
            get {
                return ResourceManager.GetString("SavedJourneyMonitorON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle monitor.
        /// </summary>
        public static string SavedJourneyMonitorToggle {
            get {
                return ResourceManager.GetString("SavedJourneyMonitorToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journeys.
        /// </summary>
        public static string SavedJourneysJourneyPivot {
            get {
                return ResourceManager.GetString("SavedJourneysJourneyPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string SavedJourneysMonitoringPivot {
            get {
                return ResourceManager.GetString("SavedJourneysMonitoringPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep track of your usual travel routes here.
        /// </summary>
        public static string SavedJourneysTileTagTour {
            get {
                return ResourceManager.GetString("SavedJourneysTileTagTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved journeys.
        /// </summary>
        public static string SavedJourneysTitle {
            get {
                return ResourceManager.GetString("SavedJourneysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select direction.
        /// </summary>
        public static string SelBusRouteDirection {
            get {
                return ResourceManager.GetString("SelBusRouteDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Direction.
        /// </summary>
        public static string SelectDirection {
            get {
                return ResourceManager.GetString("SelectDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercity bus delays.
        /// </summary>
        public static string SelSendAlertInter {
            get {
                return ResourceManager.GetString("SelSendAlertInter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rovereto bus delays.
        /// </summary>
        public static string SelSendAlertRv {
            get {
                return ResourceManager.GetString("SelSendAlertRv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a delay for buses in Rovereto.
        /// </summary>
        public static string SelSendAlertRvDesc {
            get {
                return ResourceManager.GetString("SelSendAlertRvDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an alert.
        /// </summary>
        public static string SelSendAlertTitle {
            get {
                return ResourceManager.GetString("SelSendAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trento bus delays.
        /// </summary>
        public static string SelSendAlertTn {
            get {
                return ResourceManager.GetString("SelSendAlertTn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a delay for buses in Trento.
        /// </summary>
        public static string SelSendAlertTnDesc {
            get {
                return ResourceManager.GetString("SelSendAlertTnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train delays.
        /// </summary>
        public static string SelSendAlertTrain {
            get {
                return ResourceManager.GetString("SelSendAlertTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a delay for trains.
        /// </summary>
        public static string SelSendAlertTrainDesc {
            get {
                return ResourceManager.GetString("SelSendAlertTrainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string SettignsErrorReport {
            get {
                return ResourceManager.GetString("SettignsErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add place.
        /// </summary>
        public static string SettingsPageAddPlace {
            get {
                return ResourceManager.GetString("SettingsPageAddPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My locations.
        /// </summary>
        public static string SettingsPageFavs {
            get {
                return ResourceManager.GetString("SettingsPageFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location service.
        /// </summary>
        public static string SettingsPageLocation {
            get {
                return ResourceManager.GetString("SettingsPageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SettingsPagePrefs {
            get {
                return ResourceManager.GetString("SettingsPagePrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop times.
        /// </summary>
        public static string ShowStopTimes {
            get {
                return ResourceManager.GetString("ShowStopTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string SubAlertDelay {
            get {
                return ResourceManager.GetString("SubAlertDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string SubAlertRoute {
            get {
                return ResourceManager.GetString("SubAlertRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string SubAlertStop {
            get {
                return ResourceManager.GetString("SubAlertStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubAlertSubmit {
            get {
                return ResourceManager.GetString("SubAlertSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string SubAlertTime {
            get {
                return ResourceManager.GetString("SubAlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report delays, accidents or deviations.
        /// </summary>
        public static string SubmitAlertTileTagTour {
            get {
                return ResourceManager.GetString("SubmitAlertTileTagTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recurrent journey has been changed. Do you want to save changes?.
        /// </summary>
        public static string SureChange {
            get {
                return ResourceManager.GetString("SureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application need to access to your location.
        /// </summary>
        public static string SystemLocationDisabledCaption {
            get {
                return ResourceManager.GetString("SystemLocationDisabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is disabled on your device. To enable location, go to Settings and select location..
        /// </summary>
        public static string SystemLocationDisabledMessage {
            get {
                return ResourceManager.GetString("SystemLocationDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trentino External Bus.
        /// </summary>
        public static string TileExtraurbanoMessage {
            get {
                return ResourceManager.GetString("TileExtraurbanoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trentino Bus.
        /// </summary>
        public static string TileExtraurbanoTitle {
            get {
                return ResourceManager.GetString("TileExtraurbanoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkings.
        /// </summary>
        public static string TileParkingMessage {
            get {
                return ResourceManager.GetString("TileParkingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkings.
        /// </summary>
        public static string TileParkingTitle {
            get {
                return ResourceManager.GetString("TileParkingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a single journey.
        /// </summary>
        public static string TilePlanJourneyMessage {
            get {
                return ResourceManager.GetString("TilePlanJourneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan your next trip here.
        /// </summary>
        public static string TilePlanJourneyTagTour {
            get {
                return ResourceManager.GetString("TilePlanJourneyTagTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan journey.
        /// </summary>
        public static string TilePlanJourneyTitle {
            get {
                return ResourceManager.GetString("TilePlanJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a recurrent journey.
        /// </summary>
        public static string TilePlanRecurrentJourneyMessage {
            get {
                return ResourceManager.GetString("TilePlanRecurrentJourneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan recurrent journey.
        /// </summary>
        public static string TilePlanRecurrentJourneyTitle {
            get {
                return ResourceManager.GetString("TilePlanRecurrentJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all notifications.
        /// </summary>
        public static string TileReadNotificationsMessage {
            get {
                return ResourceManager.GetString("TileReadNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read notification.
        /// </summary>
        public static string TileReadNotificationsTitle {
            get {
                return ResourceManager.GetString("TileReadNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show realtime info.
        /// </summary>
        public static string TileRealTimeInfoMessage {
            get {
                return ResourceManager.GetString("TileRealTimeInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time info.
        /// </summary>
        public static string TileRealTimeInfoTitle {
            get {
                return ResourceManager.GetString("TileRealTimeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rovereto City Bus.
        /// </summary>
        public static string TileRoveretoBusMessage {
            get {
                return ResourceManager.GetString("TileRoveretoBusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rovereto Bus.
        /// </summary>
        public static string TileRoveretoBusTitle {
            get {
                return ResourceManager.GetString("TileRoveretoBusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my saved journeys.
        /// </summary>
        public static string TileSavedJourneysMessage {
            get {
                return ResourceManager.GetString("TileSavedJourneysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved journeys.
        /// </summary>
        public static string TileSavedJourneysTitle {
            get {
                return ResourceManager.GetString("TileSavedJourneysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an alert.
        /// </summary>
        public static string TileSubmitAlertMessage {
            get {
                return ResourceManager.GetString("TileSubmitAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit alert.
        /// </summary>
        public static string TileSubmitAlertTitle {
            get {
                return ResourceManager.GetString("TileSubmitAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trentino Trains.
        /// </summary>
        public static string TileTrainMessage {
            get {
                return ResourceManager.GetString("TileTrainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string TileTrainTitle {
            get {
                return ResourceManager.GetString("TileTrainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trento City Bus.
        /// </summary>
        public static string TileTrentoBusMessage {
            get {
                return ResourceManager.GetString("TileTrentoBusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trento Bus.
        /// </summary>
        public static string TileTrentoBusTitle {
            get {
                return ResourceManager.GetString("TileTrentoBusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        public static string TimetableNotAvailable {
            get {
                return ResourceManager.GetString("TimetableNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line type.
        /// </summary>
        public static string TimeTablePageLineType {
            get {
                return ResourceManager.GetString("TimeTablePageLineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToCapitalT {
            get {
                return ResourceManager.GetString("ToCapitalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train lines.
        /// </summary>
        public static string TrainLinesTitle {
            get {
                return ResourceManager.GetString("TrainLinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ValidationBtnOk {
            get {
                return ResourceManager.GetString("ValidationBtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect values.
        /// </summary>
        public static string ValidationCaption {
            get {
                return ResourceManager.GetString("ValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a delay value.
        /// </summary>
        public static string ValidationDelay {
            get {
                return ResourceManager.GetString("ValidationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a starting point.
        /// </summary>
        public static string ValidationFrom {
            get {
                return ResourceManager.GetString("ValidationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid name for the journey.
        /// </summary>
        public static string ValidationJTitle {
            get {
                return ResourceManager.GetString("ValidationJTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors have been detected in the form data.
        /// </summary>
        public static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one day.
        /// </summary>
        public static string ValidationSelDays {
            get {
                return ResourceManager.GetString("ValidationSelDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not plan a journey in the past.
        /// </summary>
        public static string ValidationStartDate {
            get {
                return ResourceManager.GetString("ValidationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size for the timespan is of two hours.
        /// </summary>
        public static string ValidationTimeSpan {
            get {
                return ResourceManager.GetString("ValidationTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a destination.
        /// </summary>
        public static string ValidationTo {
            get {
                return ResourceManager.GetString("ValidationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one transportation type.
        /// </summary>
        public static string ValidationTType {
            get {
                return ResourceManager.GetString("ValidationTType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
    }
}
