//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaggiaTrentino.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViaggiaTrentino.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViaggiaTrentino.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike.
        /// </summary>
        public static string GeneralSettingsBike {
            get {
                return ResourceManager.GetString("GeneralSettingsBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string GeneralSettingsCar {
            get {
                return ResourceManager.GetString("GeneralSettingsCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        public static string GeneralSettingsFastest {
            get {
                return ResourceManager.GetString("GeneralSettingsFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fewest changes.
        /// </summary>
        public static string GeneralSettingsFewestChanges {
            get {
                return ResourceManager.GetString("GeneralSettingsFewestChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least walking.
        /// </summary>
        public static string GeneralSettingsLeastWalking {
            get {
                return ResourceManager.GetString("GeneralSettingsLeastWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred route.
        /// </summary>
        public static string GeneralSettingsPrefRoute {
            get {
                return ResourceManager.GetString("GeneralSettingsPrefRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared bike.
        /// </summary>
        public static string GeneralSettingsSharedBike {
            get {
                return ResourceManager.GetString("GeneralSettingsSharedBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared car.
        /// </summary>
        public static string GeneralSettingsSharedCar {
            get {
                return ResourceManager.GetString("GeneralSettingsSharedCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit.
        /// </summary>
        public static string GeneralSettingsTransit {
            get {
                return ResourceManager.GetString("GeneralSettingsTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string GeneralSettingsTransportation {
            get {
                return ResourceManager.GetString("GeneralSettingsTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string GeneralSettingsWalking {
            get {
                return ResourceManager.GetString("GeneralSettingsWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViaggiaTrentino.
        /// </summary>
        public static string MainViewTitle {
            get {
                return ResourceManager.GetString("MainViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string MonitorJourneyAlways {
            get {
                return ResourceManager.GetString("MonitorJourneyAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string MonitorJourneyLoc {
            get {
                return ResourceManager.GetString("MonitorJourneyLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preferences.
        /// </summary>
        public static string MonitorJourneyPrefs {
            get {
                return ResourceManager.GetString("MonitorJourneyPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string MonitorJourneySched {
            get {
                return ResourceManager.GetString("MonitorJourneySched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time span.
        /// </summary>
        public static string MonitorJourneyTimeSpan {
            get {
                return ResourceManager.GetString("MonitorJourneyTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor journey.
        /// </summary>
        public static string MonitorJourneyTitle {
            get {
                return ResourceManager.GetString("MonitorJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string ParkingsPageMapPivot {
            get {
                return ResourceManager.GetString("ParkingsPageMapPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkings.
        /// </summary>
        public static string ParkingsPageParkingPivot {
            get {
                return ResourceManager.GetString("ParkingsPageParkingPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time info.
        /// </summary>
        public static string ParkingsPageTitle {
            get {
                return ResourceManager.GetString("ParkingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full.
        /// </summary>
        public static string ParkingsSlotsFull {
            get {
                return ResourceManager.GetString("ParkingsSlotsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string PlanSingleJourneyDeparture {
            get {
                return ResourceManager.GetString("PlanSingleJourneyDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From....
        /// </summary>
        public static string PlanSingleJourneyHintFrom {
            get {
                return ResourceManager.GetString("PlanSingleJourneyHintFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To....
        /// </summary>
        public static string PlanSingleJourneyHintTo {
            get {
                return ResourceManager.GetString("PlanSingleJourneyHintTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string PlanSingleJourneyLoc {
            get {
                return ResourceManager.GetString("PlanSingleJourneyLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preferences.
        /// </summary>
        public static string PlanSingleJourneyPrefs {
            get {
                return ResourceManager.GetString("PlanSingleJourneyPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan new journey.
        /// </summary>
        public static string PlanSingleJourneyTitle {
            get {
                return ResourceManager.GetString("PlanSingleJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time Information.
        /// </summary>
        public static string RealTimeInfoViewTitle {
            get {
                return ResourceManager.GetString("RealTimeInfoViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete journey.
        /// </summary>
        public static string SavedJourneyDetailsDelete {
            get {
                return ResourceManager.GetString("SavedJourneyDetailsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable monitoring.
        /// </summary>
        public static string SavedJourneyDetailsMonitorOff {
            get {
                return ResourceManager.GetString("SavedJourneyDetailsMonitorOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable monitoring.
        /// </summary>
        public static string SavedJourneyDetailsMonitorOn {
            get {
                return ResourceManager.GetString("SavedJourneyDetailsMonitorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journeys.
        /// </summary>
        public static string SavedJourneysJourneyPivot {
            get {
                return ResourceManager.GetString("SavedJourneysJourneyPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string SavedJourneysMonitoringPivot {
            get {
                return ResourceManager.GetString("SavedJourneysMonitoringPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved journeys.
        /// </summary>
        public static string SavedJourneysTitle {
            get {
                return ResourceManager.GetString("SavedJourneysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is disabled in phone settings..
        /// </summary>
        public static string ServiceLocationDisabled {
            get {
                return ResourceManager.GetString("ServiceLocationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My locations.
        /// </summary>
        public static string SettingsPageFavs {
            get {
                return ResourceManager.GetString("SettingsPageFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SettingsPagePrefs {
            get {
                return ResourceManager.GetString("SettingsPagePrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trentino External Bus.
        /// </summary>
        public static string TileExtraurbanoMessage {
            get {
                return ResourceManager.GetString("TileExtraurbanoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trentino Bus.
        /// </summary>
        public static string TileExtraurbanoTitle {
            get {
                return ResourceManager.GetString("TileExtraurbanoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkings.
        /// </summary>
        public static string TileParkingMessage {
            get {
                return ResourceManager.GetString("TileParkingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkings.
        /// </summary>
        public static string TileParkingTitle {
            get {
                return ResourceManager.GetString("TileParkingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a single journey.
        /// </summary>
        public static string TilePlanJourneyMessagTilePlanJourneyMessagTilePlanJourneyMessageTilePlanJourneyMessage {
            get {
                return ResourceManager.GetString("TilePlanJourneyMessagTilePlanJourneyMessagTilePlanJourneyMessageTilePlanJourneyMe" +
                        "ssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan journey.
        /// </summary>
        public static string TilePlanJourneyTitle {
            get {
                return ResourceManager.GetString("TilePlanJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a recurrent journey.
        /// </summary>
        public static string TilePlanRecurrentJourneyMessage {
            get {
                return ResourceManager.GetString("TilePlanRecurrentJourneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan recurrent journey.
        /// </summary>
        public static string TilePlanRecurrentJourneyTitle {
            get {
                return ResourceManager.GetString("TilePlanRecurrentJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all notifications.
        /// </summary>
        public static string TileReadNotificationsMessage {
            get {
                return ResourceManager.GetString("TileReadNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read notification.
        /// </summary>
        public static string TileReadNotificationsTitle {
            get {
                return ResourceManager.GetString("TileReadNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show realtime info.
        /// </summary>
        public static string TileRealTimeInfoMessage {
            get {
                return ResourceManager.GetString("TileRealTimeInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time info.
        /// </summary>
        public static string TileRealTimeInfoTitle {
            get {
                return ResourceManager.GetString("TileRealTimeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rovereto City Bus.
        /// </summary>
        public static string TileRoveretoBusMessage {
            get {
                return ResourceManager.GetString("TileRoveretoBusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rovereto Bus.
        /// </summary>
        public static string TileRoveretoBusTitle {
            get {
                return ResourceManager.GetString("TileRoveretoBusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my saved journeys.
        /// </summary>
        public static string TileSavedJourneysMessage {
            get {
                return ResourceManager.GetString("TileSavedJourneysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved journeys.
        /// </summary>
        public static string TileSavedJourneysTitle {
            get {
                return ResourceManager.GetString("TileSavedJourneysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an alert.
        /// </summary>
        public static string TileSubmitAlertMessage {
            get {
                return ResourceManager.GetString("TileSubmitAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit alert.
        /// </summary>
        public static string TileSubmitAlertTitle {
            get {
                return ResourceManager.GetString("TileSubmitAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trentino Trains.
        /// </summary>
        public static string TileTrainMessage {
            get {
                return ResourceManager.GetString("TileTrainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string TileTrainTitle {
            get {
                return ResourceManager.GetString("TileTrainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trento City Bus.
        /// </summary>
        public static string TileTrentoBusMessage {
            get {
                return ResourceManager.GetString("TileTrentoBusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trento Bus.
        /// </summary>
        public static string TileTrentoBusTitle {
            get {
                return ResourceManager.GetString("TileTrentoBusTitle", resourceCulture);
            }
        }
    }
}
